extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern u8 bob_dl_grass_rgba16[];
extern u8 bob_dl_sand_i4[];
extern u8 bob_dl_treesbackground_ci4[];
extern u8 bob_dl_treesbackground_ci4_pal_rgba16[];
extern u8 bob_dl_rockside4_i4[];
extern u8 bob_dl_mountainsidebottom_i4[];
extern u8 bob_dl_rocksurface5_i4[];
extern u8 bob_dl_rocksurface_i4[];
extern u8 bob_dl_grate_ia8[];
extern Vtx bob_dl_Floor_mesh_layer_1_vtx_0[315];
extern Gfx bob_dl_Floor_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Outer_Ring_mesh_layer_1_vtx_0[1344];
extern Gfx bob_dl_Outer_Ring_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Outer_Ring_mesh_layer_4_vtx_0[338];
extern Gfx bob_dl_Outer_Ring_mesh_layer_4_tri_0[];
extern Vtx bob_dl_Walls_mesh_layer_1_vtx_0[1200];
extern Gfx bob_dl_Walls_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Basic_mesh_layer_1_vtx_0[586];
extern Gfx bob_dl_Basic_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Basic_mesh_layer_1_vtx_1[1181];
extern Gfx bob_dl_Basic_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Basic_mesh_layer_1_vtx_2[236];
extern Gfx bob_dl_Basic_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Outer_mesh_layer_1_vtx_0[856];
extern Gfx bob_dl_Outer_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Outer_mesh_layer_1_vtx_1[428];
extern Gfx bob_dl_Outer_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_4_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_4_vtx_0[16];
extern Gfx bob_dl_Cube_mesh_layer_4_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[631];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[1519];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_0[69];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_1[32];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_0[46];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Grass_layer1[];
extern Gfx mat_revert_bob_dl_Grass_layer1[];
extern Gfx mat_bob_dl_Trees[];
extern Gfx mat_revert_bob_dl_Trees[];
extern Gfx mat_bob_dl_Rock_Side_layer1[];
extern Gfx mat_revert_bob_dl_Rock_Side_layer1[];
extern Gfx mat_bob_dl_Rock_Top_layer1[];
extern Gfx mat_revert_bob_dl_Rock_Top_layer1[];
extern Gfx mat_bob_dl_Death_Barrier[];
extern Gfx mat_revert_bob_dl_Death_Barrier[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx bob_dl_Floor_mesh_layer_1[];
extern Gfx bob_dl_Outer_Ring_mesh_layer_1[];
extern Gfx bob_dl_Outer_Ring_mesh_layer_4[];
extern Gfx bob_dl_Walls_mesh_layer_1[];
extern Gfx bob_dl_Basic_mesh_layer_1[];
extern Gfx bob_dl_Outer_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_4[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_1[];
extern Gfx bob_dl_Plane_002_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
