extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern u8 jrb_dl_rockside4_i4[];
extern u8 jrb_dl_mountainsidebottom_i4[];
extern u8 jrb_dl_grass_rgba16[];
extern u8 jrb_dl_sand_i4[];
extern Vtx jrb_dl_Plane_003_mesh_layer_1_vtx_0[1021];
extern Gfx jrb_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Plane_003_mesh_layer_1_vtx_1[445];
extern Gfx jrb_dl_Plane_003_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_Plane_004_mesh_layer_1_vtx_0[452];
extern Gfx jrb_dl_Plane_004_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_Rock_Side_layer1[];
extern Gfx mat_revert_jrb_dl_Rock_Side_layer1[];
extern Gfx mat_jrb_dl_Grass_layer1[];
extern Gfx mat_revert_jrb_dl_Grass_layer1[];
extern Gfx jrb_dl_Plane_003_mesh_layer_1[];
extern Gfx jrb_dl_Plane_004_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
